address1: "49 West 45 Street 4Fl."
aging: "Y"
anti_discrimination_human_rights: "N"
arts_culture: "N"
bbl: "1012610015"
bin: "1034242"
borough: "MANHATTAN"
bronx: "Y"
brooklyn: "Y"
business: "N"
census_tract: "96"
child_care_parent_information: "N"
city: "New York"
community_board: "5"
community_council: "4"
community_service_volunteerism: "N"
counseling_support_groups: "N"
description: "Non profit social service agency funded by city, state and federal funds providing services to youth and elderly."
disabilities: "N"
domestic_violence: "N"
education: "Y"
employment_job_training: "Y"
faith_based_organization: "N"
fax: "2128408384"
foundation: "N"
health: "N"
homelessness: "N"
housing: "Y"
immigration: "Y"
is_registered_with_the_attorney_general_s_office: "N"
latitude: "40.756087"
legal_services: "N"
lesbian_gay_bisexual_and_or_transgender: "N"
location_1: {latitude: "40.756087", longitude: "-73.981072"}
longitude: "-73.981072"
manhattan: "N"
new_york_city_agency: "N"
none_of_the_above: "N"
nonprofit: "Y"
nourl: "N"
nta: "Midtown-Midtown South                                                      "
organizationname: "HANAC, Inc."
other_government_organization: "N"
outsideloc: "N"
personal_finance_financial_education: "N"
phone: "2128408005"
postcode: "10036"
professional_association: "N"
published: "Published"
queens: "Y"
staten_island: "N"
url: "http://hanac.org"
veterans_military_families: "N"
victim_services: "Y"
youth_services: "N"